/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao_principal;

import java.awt.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import modelos.classes.classes_visao.Model_Menu;
import themes.Theme;
import visao_widgets.telas_prontas.TelaDespesas;
import visao_widgets.telas_prontas.TelaHome;
import visao_widgets.telas_prontas.TelaMovimentacoes;
import visao_widgets.telas_prontas.TelaVeiculos;

/**
 *
 * @author caioaraujocunha
 */
public class Main extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    private TelaHome telaHome;
    private TelaDespesas telaDespesas;
    private TelaVeiculos telaVeiculos;
    private  TelaMovimentacoes telaMovimentacoes;
    private javax.swing.JPanel currentPanel;

    public Main() {
        initComponents();
        menu2.initMoving(Main.this);

        telaHome = new TelaHome();
        telaVeiculos = new TelaVeiculos();
        telaDespesas = new TelaDespesas();
        telaMovimentacoes = new TelaMovimentacoes();

        addPanel(telaHome);
        currentPanel = telaHome;

        menu2.setMenuListener(type -> switchPanel(type));

        LocalDate hoje = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        labelHeaderData.setText(hoje.format(formato));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new visao_widgets.PanelBorder();
        menu2 = new visao_widgets.Menu();
        header1 = new visao_widgets.Header();
        labelHeaderData = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainContentPanel = new visao_widgets.FormPageBorder();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBorder1.setBackground(Theme.BACKGROUND
//                new Color(15,23,42)
        );

        header1.setBackground(
                new Color(30,41,59)
        );

        labelHeaderData.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        labelHeaderData.setForeground(new java.awt.Color(200, 202, 210)); // bem vindo lettering
        labelHeaderData.setText("28/10/2003");

        jLabel1.setFont(new java.awt.Font("DIN Alternate", 1, 28)); // NOI18N
        jLabel1.setForeground(Color.WHITE);
        jLabel1.setText("Bem-Vindo!");

        javax.swing.GroupLayout header1Layout = new javax.swing.GroupLayout(header1);
        header1.setLayout(header1Layout);
        header1Layout.setHorizontalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 605, Short.MAX_VALUE)
                .addComponent(labelHeaderData)
                .addGap(23, 23, 23))
        );
        header1Layout.setVerticalGroup(
            header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelHeaderData, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainContentPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelBorder1Layout.setVerticalGroup(
            panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorder1Layout.createSequentialGroup()
                        .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainContentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {

        try {
            FlatMacDarkLaf.setup();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    private void switchPanel(Model_Menu.MenuType type) {
        switch (type) {
            case HOME:
                currentPanel = telaHome;
                ((TelaHome) currentPanel).atualizarDashboard();
                break;
            case VEICULOS:
                currentPanel = telaVeiculos;
                break;
            case DESPESAS:
                currentPanel = telaDespesas;
                break;
            case MOVIMENTACOES:
                currentPanel = telaMovimentacoes;
                break;
            default:
                currentPanel = telaHome;
                break;
        }

        addPanel(currentPanel);
    }

    private void addPanel(javax.swing.JPanel panel) {
        mainContentPanel.removeAll();

        mainContentPanel.add(panel, java.awt.BorderLayout.CENTER);
        mainContentPanel.revalidate();
        mainContentPanel.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private visao_widgets.Header header1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelHeaderData;
    private visao_widgets.FormPageBorder mainContentPanel;
    private visao_widgets.Menu menu2;
    private visao_widgets.PanelBorder panelBorder1;
    // End of variables declaration//GEN-END:variables
}
