/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao_widgets.telas_prontas;

import controle.ControladoraDespesas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

import javax.swing.JButton;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import modelos.classes.classes_visao.ScrollBar;

/**
 *
 * @author caioaraujocunha
 */
public class TelaDespesas extends javax.swing.JPanel {

    /**
     * Creates new form TelaVeiculos
     */
    private ControladoraDespesas controladora;

    public TelaDespesas() {
        initComponents();
        controladora = new ControladoraDespesas();
        setOpaque(false);
        tabela1.setOpaque(false);

        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        jScrollPane1.setVerticalScrollBar(new ScrollBar());
        jScrollPane1.getVerticalScrollBar().setBackground(Color.white);

        btDeletar.setEnabled(false);
        btEditar.setEnabled(false);
        this.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telaVeiculosMouseClicked(evt);
            }
        });

        tabela1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    controlarEstadoBotao(btDeletar);
                    controlarEstadoBotao(btEditar);
                }
            }
        });
        carregarDadosNaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorder1 = new visao_widgets.PanelBorder();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new modelos.classes.classes_visao.Tabela();
        btAdd = new javax.swing.JButton();
        btDeletar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        panelBorder1.setBackground(new java.awt.Color(255, 255, 255));

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null },
                        { null, null },
                        { null, null },
                        { null, null }
                },
                new String[] {
                        "ID", "Descrição"
                }));
        jScrollPane1.setViewportView(tabela1);

        btAdd.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_add.png"))); // NOI18N
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        btDeletar.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_deletar.png"))); // NOI18N
        btDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletarActionPerformed(evt);
            }
        });

        btEditar.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_editar.png"))); // NOI18N
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorder1Layout = new javax.swing.GroupLayout(panelBorder1);
        panelBorder1.setLayout(panelBorder1Layout);
        panelBorder1Layout.setHorizontalGroup(
                panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                        .addGroup(panelBorder1Layout.createSequentialGroup()
                                .addComponent(btAdd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDeletar)));
        panelBorder1Layout.setVerticalGroup(
                panelBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorder1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelBorder1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btDeletar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btEditar, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btAdd, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 391,
                                        Short.MAX_VALUE)));

        add(panelBorder1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btAddActionPerformed
        try {
            visao_widgets.paineis_de_telas.AdicionarDespesaPanel formPanel = new visao_widgets.paineis_de_telas.AdicionarDespesaPanel(
                    tabela1);

            javax.swing.JDialog dialog = new javax.swing.JDialog(
                    (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
                    "Adicionar Despesa",
                    true // Modal
            );

            dialog.setContentPane(formPanel);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            carregarDadosNaTabela();

        } catch (Exception erro) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao carregar ou editar dados da despesa:\n" + erro.getMessage(),
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btAddActionPerformed

    private void btDeletarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btDeletarActionPerformed
        int selectedRow = tabela1.getSelectedRow();

        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma despesa para deletar!",
                    "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object id = tabela1.getValueAt(selectedRow, 0);
        String despesaID = id.toString();

        try {
            controladora.removerDespesa(despesaID, tabela1);

            javax.swing.JOptionPane.showMessageDialog(this, "Sua despesa foi deletada com sucesso.",
                    "Sucesso!", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception erro) {
            String msg = "Persistência - Método Deletar Despesa - " + erro.getMessage();
            System.out.println(msg);

            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao deletar despesa:\n" + erro.getMessage(),
                    "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btDeletarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btEditarActionPerformed
        int selectedRow = tabela1.getSelectedRow();

        if (selectedRow < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um veículo para editar!",
                    "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object id = tabela1.getValueAt(selectedRow, 0);
        String despesaID = id.toString();

        try {
            visao_widgets.paineis_de_telas.EditarDespesaPanel formPanel = new visao_widgets.paineis_de_telas.EditarDespesaPanel(
                    tabela1);

            formPanel.carregarDados(despesaID);

            javax.swing.JDialog dialog = new javax.swing.JDialog(
                    (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this),
                    "Editar Despesa: " + despesaID,
                    true // Modal
            );

            dialog.setContentPane(formPanel);
            dialog.pack();
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            carregarDadosNaTabela();

        } catch (Exception erro) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao carregar ou editar dados da despesa:\n" + erro.getMessage(),
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btEditarActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 40, 40);
        super.paintComponent(g);
    }

    private void carregarDadosNaTabela() {
        try {
            controladora.carregarTabela(tabela1);
        } catch (Exception erro) {
            String msg = "Persistencia - Metodo Cadastrar Movimentacao - " + erro.getMessage();
            System.out.println(msg);
        }
    }

    private void controlarEstadoBotao(JButton bt) {
        boolean hasSelection = tabela1.getSelectedRow() != -1;

        bt.setEnabled(hasSelection);
    }

    private void telaVeiculosMouseClicked(java.awt.event.MouseEvent evt) {
        java.awt.Component clickedComponent = evt.getComponent().getComponentAt(evt.getPoint());

        if (clickedComponent != tabela1 && clickedComponent != jScrollPane1) {
            tabela1.clearSelection();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btDeletar;
    private javax.swing.JButton btEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private visao_widgets.PanelBorder panelBorder1;
    private modelos.classes.classes_visao.Tabela tabela1;
    // End of variables declaration//GEN-END:variables
}
