/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao_widgets.paineis_de_telas;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.SwingUtilities;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

import controle.ControladoraVeiculos;
import modelos.classes.EstadoDoVeiculo;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author caioaraujocunha
 */
public class AdicionarVeiculoPanel extends javax.swing.JPanel {

        private ControladoraVeiculos controladora;
        private JTable tabelaVeiculos;

        /**
         * Creates new form EditarVeiculoPanel
         */
        public AdicionarVeiculoPanel(JTable tabelaVeiculos) {
                this.tabelaVeiculos = tabelaVeiculos;
                this.controladora = new ControladoraVeiculos();
                initComponents();
                setOpaque(false);

                // Aplica a máscara/filtro no campo de placa para aceitar apenas 7 caracteres
                // alfanuméricos e em maiúsculo
                configurarFiltroPlaca();

                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
        }

        private void configurarFiltroPlaca() {
                ((AbstractDocument) textFieldPlaca.getDocument()).setDocumentFilter(new DocumentFilter() {
                        @Override
                        public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr)
                                        throws BadLocationException {
                                if (string == null)
                                        return;
                                String text = string.replaceAll("[^a-zA-Z0-9]", "").toUpperCase();
                                if ((fb.getDocument().getLength() + text.length()) <= 7) {
                                        super.insertString(fb, offset, text, attr);
                                }
                        }

                        @Override
                        public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs)
                                        throws BadLocationException {
                                if (text == null)
                                        return;
                                String cleanedText = text.replaceAll("[^a-zA-Z0-9]", "").toUpperCase();
                                if ((fb.getDocument().getLength() + cleanedText.length() - length) <= 7) {
                                        super.replace(fb, offset, length, cleanedText, attrs);
                                }
                        }
                });
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel4 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                textFieldPlaca = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                comboBoxMarca = new javax.swing.JComboBox<>();
                jLabel5 = new javax.swing.JLabel();
                textFieldModelo = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                textFieldAno = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox<>();
                jLabel8 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();

                setBackground(new java.awt.Color(220, 227, 238));

                jLabel4.setFont(new java.awt.Font("DIN Alternate", 0, 30)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 139, 0));
                jLabel4.setText("GynLog");

                jLabel1.setFont(new java.awt.Font("DIN Alternate", 1, 18)); // NOI18N
                jLabel1.setText("Soluções");

                jLabel2.setBackground(new java.awt.Color(255, 153, 0));
                jLabel2.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 139, 0));
                jLabel2.setText("Placa");

                jLabel3.setBackground(new java.awt.Color(255, 153, 0));
                jLabel3.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 139, 0));
                jLabel3.setText("Marca");

                comboBoxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Selecione...", "Chevrolet", "Fiat", "Ford", "Honda", "Hyundai", "Citroën",
                                                "Nissan", "Renault", "Toyota", "Volkswagen", "BYD", "Peugeot"  }));

                jLabel5.setBackground(new java.awt.Color(255, 153, 0));
                jLabel5.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 139, 0));
                jLabel5.setText("Modelo");

                textFieldModelo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textFieldModeloActionPerformed(evt);
                        }
                });

                jLabel6.setBackground(new java.awt.Color(255, 153, 0));
                jLabel6.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 139, 0));
                jLabel6.setText("Ano");

                textFieldAno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textFieldAnoActionPerformed(evt);
                        }
                });

                jLabel7.setBackground(new java.awt.Color(255, 153, 0));
                jLabel7.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 139, 0));
                jLabel7.setText("Estado");

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO" }));
                jComboBox1.setBorder(null);

                jLabel8.setFont(new java.awt.Font("DIN Alternate", 0, 24)); // NOI18N
                jLabel8.setText("Adicionar Veículo");

                jButton1.setText("Adicionar");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton1))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(31, 31, 31)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel7)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                25,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(jComboBox1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                403,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel6)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(textFieldAno,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                403,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                .addComponent(jLabel3))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(comboBoxMarca,
                                                                                                                                                                0,
                                                                                                                                                                403,
                                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                                .addComponent(textFieldModelo)))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel2)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(textFieldPlaca,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                403,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel8)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jLabel4,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))))))
                                                                .addGap(16, 16, 16)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(20, 20, 20)
                                                                                                .addComponent(jLabel4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                34,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, 0)
                                                                                                .addComponent(jLabel1)
                                                                                                .addGap(58, 58, 58))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(36, 36, 36)
                                                                                                .addComponent(jLabel8,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(textFieldPlaca,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2))
                                                                .addGap(28, 28, 28)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(comboBoxMarca,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(textFieldModelo,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(textFieldAno,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(jComboBox1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton1)
                                                                .addGap(30, 30, 30)));
        }// </editor-fold>//GEN-END:initComponents

        private void textFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldModeloActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_textFieldModeloActionPerformed

        private void textFieldAnoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldAnoActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_textFieldAnoActionPerformed

        @Override
        protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());

                // CORREÇÃO DO FUNDO ESCURO: Preenche o retângulo antes do super
                // g2.fillRect(0, 0, getWidth(), getHeight());

                super.paintComponent(g);
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                String placa = textFieldPlaca.getText().trim().toUpperCase();
                String marca = comboBoxMarca.getSelectedItem().toString();
                String modelo = capitalizeWords(textFieldModelo.getText());
                String anoStr = textFieldAno.getText().trim();

                EstadoDoVeiculo estado = EstadoDoVeiculo.valueOf(jComboBox1.getSelectedItem().toString());

                // Validação de campos vazios ou não selecionados
                if (placa.isEmpty() || marca.equals("Selecione...") || modelo.isEmpty() || anoStr.isEmpty()) {
                        JOptionPane.showMessageDialog(this,
                                        "Todos os campos (Placa, Marca, Modelo, Ano) devem ser preenchidos/selecionados.",
                                        "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                        return;
                }

                // EXPRESSÃO REGULAR DA PLACA:
                // ^[A-Z]{3} -> Começa obrigatoriamente com 3 letras
                // [0-9] -> Seguido por 1 número
                // [A-Z0-9] -> 5ª posição aceita letra (Mercosul) ou número (Tradicional)
                // [0-9]{2}$ -> Termina estritamente com 2 números
                if (!placa.matches("^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$")) {
                        JOptionPane.showMessageDialog(this,
                                        "Formato de Placa Inválido!\nExemplos aceitos:\n- Tradicional: ABC1234\n- Mercosul: ABC1D23",
                                        "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                        return;
                }

                if (anoStr.length() != 4) {
                        JOptionPane.showMessageDialog(this,
                                        "O campo Ano deve conter exatamente 4 dígitos (ex: 2026).",
                                        "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                        return;
                }

                try {
                        int ano = Integer.parseInt(anoStr);
                        controladora.incluirVeiculo(placa, marca, modelo, ano, estado, tabelaVeiculos);

                        JDialog dialog = (JDialog) SwingUtilities.getWindowAncestor(this);
                        dialog.dispose();

                        JOptionPane.showMessageDialog(null,
                                        "Dados do veículo atualizados com sucesso!",
                                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this,
                                        "Erro: O campo Ano deve ser um número inteiro (ex: 2026).",
                                        "Erro de Formato", JOptionPane.ERROR_MESSAGE);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this,
                                        "Erro ao atualizar veículo:\n" + e.getMessage(),
                                        "Erro de Persistência", JOptionPane.ERROR_MESSAGE);
                }
        }

        public static String capitalizeWords(String str) {
                if (str == null || str.isEmpty())
                        return str;

                String[] words = str.trim().toLowerCase().split("\\s+");
                StringBuilder capitalized = new StringBuilder();

                for (String word : words) {
                        if (word.length() > 0) {
                                capitalized.append(Character.toUpperCase(word.charAt(0)))
                                                .append(word.substring(1))
                                                .append(" ");
                        }
                }

                return capitalized.toString().trim();
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JComboBox<String> comboBoxMarca;
        private javax.swing.JButton jButton1;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JTextField textFieldAno;
        private javax.swing.JTextField textFieldModelo;
        private javax.swing.JTextField textFieldPlaca;
        // End of variables declaration//GEN-END:variables
}