/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao_widgets.paineis_de_telas;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.SwingUtilities;

import controle.ControladoraDespesas;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author caioaraujocunha
 */
public class AdicionarDespesaPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditarVeiculoPanel
     */
    private ControladoraDespesas controladora;
    private JTable tabelaDespesas;

    public AdicionarDespesaPanel(JTable tabelaDespesas) {
        this.tabelaDespesas = tabelaDespesas;
        this.controladora = new ControladoraDespesas();
        initComponents();
        setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldDescricao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 227, 238));

        jLabel4.setFont(new java.awt.Font("DIN Alternate", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 139, 0));
        jLabel4.setText("GynLog");

        jLabel1.setFont(new java.awt.Font("DIN Alternate", 1, 18)); // NOI18N
        jLabel1.setText("Soluções");

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 139, 0));
        jLabel2.setText("Descrição");

        jLabel8.setFont(new java.awt.Font("DIN Alternate", 0, 24)); // NOI18N
        jLabel8.setText("Adicionar Despesa");

        jButton1.setText("Adicionar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1)
                        .addGap(86, 86, 86))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(textFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldMarcaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldMarcaActionPerformed

    private void textFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldModeloActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldModeloActionPerformed

    private void textFieldAnoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldAnoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldAnoActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        super.paintComponent(g);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String descricao = textFieldDescricao.getText().trim();

        if (descricao.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "O campo Descrição deve ser preenchido.",
                    "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            controladora.incluirDespesa(descricao, tabelaDespesas);

            JDialog dialog = (JDialog) SwingUtilities.getWindowAncestor(this);
            dialog.dispose();

            JOptionPane.showMessageDialog(null,
                    "Dados da despesa atualizados com sucesso!",
                    "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Erro: O campo Ano deve ser um número inteiro (ex: 2025).",
                    "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao atualizar veículo:\n" + e.getMessage(),
                    "Erro de Persistência", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textFieldDescricao;
    // End of variables declaration//GEN-END:variables
}
