/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao_widgets.paineis_de_telas;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.SwingUtilities;

import controle.ControladoraVeiculos;
import modelos.classes.EstadoDoVeiculo;
import modelos.classes.Veiculo;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author caioaraujocunha
 */
public class EditarVeiculoPanel extends javax.swing.JPanel {

        /**
         * Creates new form EditarVeiculoPanel
         */
        private String veiculoIDAtual;
        private ControladoraVeiculos controladora;
        private JTable tabelaVeiculos;

        public EditarVeiculoPanel(JTable tabelaVeiculos) {
                this.tabelaVeiculos = tabelaVeiculos;
                this.controladora = new ControladoraVeiculos();
                initComponents();
                setOpaque(false);
                jButton1.addActionListener(new java.awt.event.ActionListener() {

                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel4 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                textFieldPlaca = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                textFieldMarca = new javax.swing.JTextField();
                jLabel5 = new javax.swing.JLabel();
                textFieldModelo = new javax.swing.JTextField();
                jLabel6 = new javax.swing.JLabel();
                textFieldAno = new javax.swing.JTextField();
                jLabel7 = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox<>();
                jLabel8 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();

                setBackground(new java.awt.Color(220, 227, 238));

                jLabel4.setFont(new java.awt.Font("DIN Alternate", 0, 30)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 139, 0));
                jLabel4.setText("GynLog");

                jLabel1.setFont(new java.awt.Font("DIN Alternate", 1, 18)); // NOI18N
                jLabel1.setText("Soluções");

                jLabel2.setBackground(new java.awt.Color(255, 153, 0));
                jLabel2.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 139, 0));
                jLabel2.setText("Placa");

                textFieldPlaca.setText("--Digite a placa do veículo--");

                jLabel3.setBackground(new java.awt.Color(255, 153, 0));
                jLabel3.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 139, 0));
                jLabel3.setText("Marca");

                textFieldMarca.setText("--Digite a marca do veículo--");
                textFieldMarca.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textFieldMarcaActionPerformed(evt);
                        }
                });

                jLabel5.setBackground(new java.awt.Color(255, 153, 0));
                jLabel5.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(255, 139, 0));
                jLabel5.setText("Modelo");

                textFieldModelo.setText("--Digite o modelo do veículo--");
                textFieldModelo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textFieldModeloActionPerformed(evt);
                        }
                });

                jLabel6.setBackground(new java.awt.Color(255, 153, 0));
                jLabel6.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(255, 139, 0));
                jLabel6.setText("Ano");

                textFieldAno.setText("--Digite o ano do veículo--");
                textFieldAno.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                textFieldAnoActionPerformed(evt);
                        }
                });

                jLabel7.setBackground(new java.awt.Color(255, 153, 0));
                jLabel7.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
                jLabel7.setForeground(new java.awt.Color(255, 139, 0));
                jLabel7.setText("Estado");

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO" }));

                jLabel8.setFont(new java.awt.Font("DIN Alternate", 0, 24)); // NOI18N
                jLabel8.setText("Editar Veículo");

                jButton1.setText("Atualizar dados");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addContainerGap(
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton1))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(31, 31, 31)
                                                                                                .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel7)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                25,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(jComboBox1,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                403,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel6)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(textFieldAno,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                403,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel5)
                                                                                                                                                .addComponent(jLabel3))
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                                                false)
                                                                                                                                                .addComponent(textFieldMarca)
                                                                                                                                                .addComponent(textFieldModelo,
                                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                403,
                                                                                                                                                                Short.MAX_VALUE)))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel2)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addComponent(textFieldPlaca,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                403,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                                                .addComponent(jLabel8,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                142,
                                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                Short.MAX_VALUE)
                                                                                                                                .addGroup(layout.createParallelGroup(
                                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                                                .addComponent(jLabel1,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                .addComponent(jLabel4,
                                                                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING))))))
                                                                .addGap(16, 16, 16)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(20, 20, 20)
                                                                                                .addComponent(jLabel4,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                34,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0, 0)
                                                                                                .addComponent(jLabel1)
                                                                                                .addGap(58, 58, 58))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(36, 36, 36)
                                                                                                .addComponent(jLabel8,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(textFieldPlaca,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel2))
                                                                .addGap(28, 28, 28)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel3)
                                                                                .addComponent(textFieldMarca,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel5)
                                                                                .addComponent(textFieldModelo,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(29, 29, 29)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel6)
                                                                                .addComponent(textFieldAno,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(27, 27, 27)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(jLabel7)
                                                                                .addComponent(jComboBox1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton1)
                                                                .addGap(30, 30, 30)));
        }// </editor-fold>//GEN-END:initComponents

        private void textFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldMarcaActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_textFieldMarcaActionPerformed

        private void textFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldModeloActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_textFieldModeloActionPerformed

        private void textFieldAnoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldAnoActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_textFieldAnoActionPerformed

        @Override
        protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2.setColor(getBackground());
                super.paintComponent(g);
        }

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
                String placa = textFieldPlaca.getText().trim();
                String marca = capitalizeWords(textFieldMarca.getText());
                String modelo = capitalizeWords(textFieldModelo.getText());
                String anoStr = textFieldAno.getText().trim();

                EstadoDoVeiculo estado = EstadoDoVeiculo.valueOf(jComboBox1.getSelectedItem().toString());

                if (placa.isEmpty() || marca.isEmpty() || modelo.isEmpty() || anoStr.isEmpty()) {
                        JOptionPane.showMessageDialog(this,
                                        "Todos os campos (Placa, Marca, Modelo, Ano) devem ser preenchidos.",
                                        "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                        return;
                }

                if (anoStr.length() != 4) {
                        JOptionPane.showMessageDialog(this,
                                        "O campo Ano deve conter exatamente 4 dígitos (ex: 2025).",
                                        "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                        return;
                }

                try {
                        int ano = Integer.parseInt(anoStr);

                        Veiculo veiculoAtualizado = new Veiculo(
                                        this.veiculoIDAtual,
                                        placa,
                                        marca,
                                        modelo,
                                        ano,
                                        estado);

                        controladora.atualizarVeiculo(veiculoAtualizado, tabelaVeiculos);

                        JDialog dialog = (JDialog) SwingUtilities.getWindowAncestor(this);
                        dialog.dispose();

                        JOptionPane.showMessageDialog(null,
                                        "Dados do veículo atualizados com sucesso!",
                                        "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                } catch (NumberFormatException e) {
                        JOptionPane.showMessageDialog(this,
                                        "Erro: O campo Ano deve ser um número inteiro (ex: 2025).",
                                        "Erro de Formato", JOptionPane.ERROR_MESSAGE);
                } catch (Exception e) {
                        JOptionPane.showMessageDialog(this,
                                        "Erro ao atualizar veículo:\n" + e.getMessage(),
                                        "Erro de Persistência", JOptionPane.ERROR_MESSAGE);
                }
        }

        public void carregarDados(String veiculoID) throws Exception {
                this.veiculoIDAtual = veiculoID;
                Veiculo veiculo = controladora.buscarVeiculoPorId(veiculoID);

                if (veiculo != null) {
                        textFieldPlaca.setText(veiculo.getPlaca());
                        textFieldMarca.setText(veiculo.getMarca());
                        textFieldModelo.setText(veiculo.getModelo());
                        textFieldAno.setText(String.valueOf(veiculo.getAnoDeFabricacao()));

                        String estado = veiculo.isEstadoDoVeiculo().name();
                        jComboBox1.setSelectedItem(estado);

                } else {
                        throw new Exception("Veículo com ID " + veiculoID + " não encontrado.");
                }
        }

        public static String capitalizeWords(String str) {
                if (str == null || str.isEmpty())
                        return str;

                String[] words = str.trim().toLowerCase().split("\\s+");
                StringBuilder capitalized = new StringBuilder();

                for (String word : words) {
                        if (word.length() > 0) {
                                capitalized.append(Character.toUpperCase(word.charAt(0)))
                                                .append(word.substring(1))
                                                .append(" ");
                        }
                }

                return capitalized.toString().trim();
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JComboBox<String> jComboBox1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JLabel jLabel8;
        private javax.swing.JTextField textFieldAno;
        private javax.swing.JTextField textFieldMarca;
        private javax.swing.JTextField textFieldModelo;
        private javax.swing.JTextField textFieldPlaca;
        // End of variables declaration//GEN-END:variables
}
