/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao_widgets.paineis_de_telas;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.SwingUtilities;

import controle.ControladoraMovimentacao;
import estruturas.ListaEncadeada;
import modelos.classes.Movimentacao;
import modelos.classes.TipoDeDespesa;
import modelos.classes.Veiculo;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author caioaraujocunha
 */
public class EditarMovimentacaoPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditarVeiculoPanel
     */
    private String movimentacaoIDAtual;
    private ControladoraMovimentacao controladora;
    private JTable tabelaMovimentacoes;
    private ListaEncadeada<Veiculo> listaVeiculos;
    private ListaEncadeada<TipoDeDespesa> listaDeDespesas; //

    public EditarMovimentacaoPanel(JTable tabelaMovimentacoes) {
        this.tabelaMovimentacoes = tabelaMovimentacoes;
        this.controladora = new ControladoraMovimentacao();
        initComponents();
        setOpaque(false);
        carregarComboBoxVeiculos();
        carregarComboBoxDespesas();
        definirDataField();

        textFieldData.setEnabled(false);
        textFieldDescricao.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        comboBoxDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxDespesaActionPerformed(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldDescricao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFieldData = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textFieldValor = new javax.swing.JTextField();
        comboBoxVeiculos = new javax.swing.JComboBox<>();
        comboBoxDespesa = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(220, 227, 238));

        jLabel4.setFont(new java.awt.Font("DIN Alternate", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 139, 0));
        jLabel4.setText("GynLog");

        jLabel1.setFont(new java.awt.Font("DIN Alternate", 1, 18)); // NOI18N
        jLabel1.setText("Soluções");

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 139, 0));
        jLabel2.setText("Veículo");

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 139, 0));
        jLabel3.setText("Despesa");

        jLabel5.setBackground(new java.awt.Color(255, 153, 0));
        jLabel5.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 139, 0));
        jLabel5.setText("Descrição");

        textFieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // textFieldDescricaoActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 153, 0));
        jLabel6.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 139, 0));
        jLabel6.setText("Data");

        textFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // textFieldDataActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 153, 0));
        jLabel7.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 139, 0));
        jLabel7.setText("Valor");

        jLabel8.setFont(new java.awt.Font("DIN Alternate", 0, 24)); // NOI18N
        jLabel8.setText("Editar Movimentação");

        jButton1.setText("Atualizar dados");

        textFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldValorActionPerformed(evt);
            }
        });

        comboBoxVeiculos.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxDespesa.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel8,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 220,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        193, Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel1,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(jLabel4,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel6)
                                                                        .addComponent(jLabel7))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(textFieldValor,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                385, Short.MAX_VALUE)
                                                                        .addComponent(textFieldData)))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel5)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(jLabel2))
                                                                .addGap(24, 24, 24)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(textFieldDescricao)
                                                                        .addComponent(comboBoxVeiculos, 0,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(comboBoxDespesa, 0,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))))))
                                .addGap(16, 16, 16)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, 0)
                                                .addComponent(jLabel1)
                                                .addGap(58, 58, 58))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(comboBoxVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(comboBoxDespesa, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(textFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel6)
                                        .addComponent(textFieldData, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel7)
                                        .addComponent(textFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)));
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldValorActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldValorActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldValorActionPerformed

    private void textFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldMarcaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldMarcaActionPerformed

    private void textFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldModeloActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldModeloActionPerformed

    private void textFieldAnoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldAnoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldAnoActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setColor(getBackground());
        super.paintComponent(g);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        String veiculoItem = (String) comboBoxVeiculos.getSelectedItem();
        String despesaItem = (String) comboBoxDespesa.getSelectedItem();

        String data = textFieldData.getText().trim();
        String valorStr = textFieldValor.getText().trim();
        String descricao = textFieldDescricao.getText().trim();

        String idDeVeiculo = null;
        String idTipoDeDespesa = null;

        if (veiculoItem != null && veiculoItem.contains(" - VEÍCULO EXCLUÍDO]")) {
            JOptionPane.showMessageDialog(this,
                    "Não é possível editar a movimentação com um Veículo marcado como 'EXCLUÍDO'.", "Erro",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (despesaItem != null && despesaItem.contains(" - DESPESA EXCLUÍDA]")) {
            JOptionPane.showMessageDialog(this,
                    "Não é possível editar a movimentação com uma Despesa marcada como 'EXCLUÍDA'.", "Erro",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (veiculoItem != null && veiculoItem.contains(" - "))
            idDeVeiculo = veiculoItem.split(" - ", 2)[0].trim();
        if (despesaItem != null && despesaItem.contains(" - "))
            idTipoDeDespesa = despesaItem.split(" - ", 2)[0].trim();

        if (idDeVeiculo == null || idTipoDeDespesa == null || veiculoItem.equals("Selecione um veículo")
                || despesaItem.equals("Selecione uma despesa") || data.isEmpty() || valorStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Selecione o veículo, a despesa e preencha a data e o valor.",
                    "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            valorStr = valorStr.replace(",", ".");
            double valor = Double.parseDouble(valorStr);
            int valorInt = (int) Math.round(valor);

            Movimentacao movAtualizada = new Movimentacao(this.movimentacaoIDAtual, idDeVeiculo, idTipoDeDespesa,
                    descricao, data, valorInt);

            // CORRIGIDO: Chama o método correto da controladora, que já atualiza o arquivo
            // e recarrega a tabela.
            controladora.atualizarMovimentacao(movAtualizada, tabelaMovimentacoes);

            JDialog dialog = (JDialog) SwingUtilities.getWindowAncestor(this);
            dialog.dispose();
            JOptionPane.showMessageDialog(null, "Movimentação atualizada com sucesso!", "Sucesso!",
                    JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar movimentação:\n" + e.getMessage(), "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    public void carregarDados(String movimentacaoID) throws Exception {
        this.movimentacaoIDAtual = movimentacaoID;
        Movimentacao movimentacao = controladora.buscarMovimentacaoPorId(movimentacaoID);
        Veiculo veiculoOriginal = controladora.buscarVeiculoPorId(movimentacao.getIdDeVeiculo());
        TipoDeDespesa despesaOriginal = controladora.buscarTipoDeDespesaPorId(movimentacao.getIdTipoDeDespesa());

        if (movimentacao != null) {
            if (veiculoOriginal != null) {
                String veiculoString = String.format("%s - %s, %s, %s, %d",
                        veiculoOriginal.getIdDeVeiculo(), veiculoOriginal.getPlaca(), veiculoOriginal.getMarca(),
                        veiculoOriginal.getModelo(), veiculoOriginal.getAnoDeFabricacao());
                comboBoxVeiculos.setSelectedItem(veiculoString);
            } else {
                String veiculoExcluidoStr = "[ID " + movimentacao.getIdDeVeiculo() + " - VEÍCULO EXCLUÍDO]";
                comboBoxVeiculos.addItem(veiculoExcluidoStr);
                comboBoxVeiculos.setSelectedItem(veiculoExcluidoStr);
            }
        }

        textFieldValor.setText(String.format("%.2f", (double) movimentacao.getValor()));

        if (despesaOriginal != null) {
            String despesaString = String.format("%s - %s", despesaOriginal.getIdTipoDeDespesa(),
                    despesaOriginal.getDescricao());
            comboBoxDespesa.setSelectedItem(despesaString);
            textFieldDescricao.setText(movimentacao.getDescricao());
            textFieldData.setText(movimentacao.getData());
        } else {
            String despesaExcluidaStr = "[ID " + movimentacao.getIdTipoDeDespesa() + " - DESPESA EXCLUÍDA]";
            comboBoxDespesa.addItem(despesaExcluidaStr);
            comboBoxDespesa.setSelectedItem(despesaExcluidaStr);
        }
    }

    private void carregarComboBoxVeiculos() {
        try {
            listaVeiculos = controladora.listarVeiculos();
            comboBoxVeiculos.removeAllItems();

            if (listaVeiculos.estaVazia()) { // .isEmpty() alterado para .estaVazia()
                comboBoxVeiculos.addItem("Nenhum veículo disponível");
                return;
            }

            comboBoxVeiculos.addItem("Selecione um veículo");
            comboBoxVeiculos.setSelectedIndex(0);

            for (Veiculo v : listaVeiculos) {
                String itemFormatado = String.format("%s - %s, %s, %s, %d",
                        v.getIdDeVeiculo(), v.getPlaca(), v.getMarca(), v.getModelo(), v.getAnoDeFabricacao());
                comboBoxVeiculos.addItem(itemFormatado);
            }
        } catch (Exception e) {
            comboBoxVeiculos.removeAllItems();
            comboBoxVeiculos.addItem("Erro ao carregar dados.");
        }
    }

    private void carregarComboBoxDespesas() {
        try {
            listaDeDespesas = controladora.listarTiposDeDespesa();
            comboBoxDespesa.removeAllItems();

            if (listaDeDespesas.estaVazia()) { // .isEmpty() alterado para .estaVazia()
                comboBoxDespesa.addItem("Nenhuma despesa disponível");
                return;
            }

            comboBoxDespesa.addItem("Selecione uma despesa");
            comboBoxDespesa.setSelectedIndex(0);

            for (TipoDeDespesa d : listaDeDespesas) {
                String itemFormatado = String.format("%s - %s", d.getIdTipoDeDespesa(), d.getDescricao());
                comboBoxDespesa.addItem(itemFormatado);
            }
        } catch (Exception e) {
            comboBoxDespesa.removeAllItems();
            comboBoxDespesa.addItem("Erro ao carregar dados.");
        }
    }

    private void comboBoxDespesaActionPerformed(java.awt.event.ActionEvent evt) {
        String itemSelecionado = (String) comboBoxDespesa.getSelectedItem();
        if (itemSelecionado == null || itemSelecionado.equals("Selecione uma despesa")) {
            textFieldDescricao.setText("");
            return;
        }

        try {
            String idDespesaSelecionada = itemSelecionado.split(" - ", 2)[0].trim();
            String descricao = "";
            for (TipoDeDespesa d : listaDeDespesas) {
                if (d.getIdTipoDeDespesa().equals(idDespesaSelecionada)) {
                    descricao = d.getDescricao();
                    break;
                }
            }
            textFieldDescricao.setText(descricao);
        } catch (Exception e) {
            textFieldDescricao.setText("ERRO DE CARREGAMENTO");
        }
    }

    private void definirDataField() {
        java.time.LocalDate dataAtual = java.time.LocalDate.now();
        String dataFormatada = String.format("%02d/%02d/%04d", dataAtual.getDayOfMonth(), dataAtual.getMonthValue(),
                dataAtual.getYear());
        textFieldData.setText(dataFormatada);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBoxDespesa;
    private javax.swing.JComboBox<String> comboBoxVeiculos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField textFieldData;
    private javax.swing.JTextField textFieldDescricao;
    private javax.swing.JTextField textFieldValor;
    // End of variables declaration//GEN-END:variables
}
