/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao_widgets.paineis_de_telas;

import controle.ControladoraMovimentacao;
import estruturas.ListaEncadeada;
import modelos.classes.Movimentacao;


/**
 *
 * @author caioaraujocunha
 */
public class Relatorio2 extends javax.swing.JPanel {

    /**
     * Creates new form Relatorio2
     */
    ControladoraMovimentacao controladoraMovimentacao;
    String mes;
    String ano;

    public Relatorio2() {
        initComponents();
        controladoraMovimentacao = new ControladoraMovimentacao();
        carregarMeses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBoxMes = new javax.swing.JComboBox<>();
        btGerarRelatorio = new javax.swing.JToggleButton();
        txtFieldAno = new javax.swing.JTextField();

//        setBackground(new java.awt.Color(220, 227, 238));

        jLabel4.setFont(new java.awt.Font("DIN Alternate", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 139, 0));
        jLabel4.setText("GynLog");

        jLabel1.setFont(new java.awt.Font("DIN Alternate", 1, 18)); // NOI18N
        jLabel1.setText("Soluções");

        jLabel8.setFont(new java.awt.Font("DIN Alternate", 0, 24)); // NOI18N
        jLabel8.setText("Selecione o mês e ano");

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 139, 0));
        jLabel2.setText("Mês");

        jLabel3.setBackground(new java.awt.Color(255, 153, 0));
        jLabel3.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 139, 0));
        jLabel3.setText("Ano");

        comboBoxMes.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxMesActionPerformed(evt);
            }
        });

        btGerarRelatorio.setText("Gerar Relatório");
        btGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3))
                                                .addGap(28, 28, 28)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(comboBoxMes, 0, 380, Short.MAX_VALUE)
                                                        .addComponent(txtFieldAno))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(189, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4,
                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(btGerarRelatorio)
                                                        .addGap(178, 178, 178)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel2))
                                        .addComponent(comboBoxMes, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28,
                                        Short.MAX_VALUE)
                                .addComponent(btGerarRelatorio)
                                .addGap(23, 23, 23)));
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxMesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboBoxMesActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboBoxMesActionPerformed

    private void btGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btGerarRelatorioActionPerformed
        // TODO add your handling code here:
        String mesNome = (String) comboBoxMes.getSelectedItem();
        String anoStr = txtFieldAno.getText().trim();

        if (comboBoxMes.getSelectedIndex() == 0 || anoStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um mês e insira o ano.",
                    "Erro de Validação", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int mesD = comboBoxMes.getSelectedIndex();
        int anoD;

        try {
            anoD = Integer.parseInt(anoStr);
            if (anoD < 1900 || anoD > 3000)
                throw new NumberFormatException();

            gerarRelatorio(mesD, anoD, mesNome);

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ano inválido. Use 4 dígitos numéricos.", "Erro de Formato",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao gerar o relatório: " + e.getMessage(), "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }// GEN-LAST:event_btGerarRelatorioActionPerformed

    private final String[] nomesDosMeses = {
            "Selecione o Mês", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
            "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
    };

    private void carregarMeses() {
        comboBoxMes.setModel(new javax.swing.DefaultComboBoxModel<>(nomesDosMeses));
        comboBoxMes.setSelectedIndex(0);
    }

        private void gerarRelatorio(int mes, int ano, String mesNome) throws Exception {
                try {
                // Modificado para usar ListaEncadeada
                ListaEncadeada<Movimentacao> listarMovimentacoesPorMes = controladoraMovimentacao.listarMovimentacoesPorMes(mes, ano);
                double totalGasto = controladoraMovimentacao.calcularSomatorioPorMes(listarMovimentacoesPorMes);
                controladoraMovimentacao.gerarRelatorio2MensalPDF(mes, ano, mesNome, totalGasto, listarMovimentacoesPorMes);
                } catch (Exception e) {
                throw new Exception(e.getMessage());
                }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btGerarRelatorio;
    private javax.swing.JComboBox<String> comboBoxMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtFieldAno;
    // End of variables declaration//GEN-END:variables
}
