/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao_widgets.paineis_de_telas;

import controle.ControladoraMovimentacao;
import estruturas.ListaEncadeada;
import modelos.classes.Movimentacao;
import modelos.classes.Veiculo;

/**
 *
 * @author caioaraujocunha
 */
public class Relatorio1 extends javax.swing.JPanel {

    /**
     * Creates new form Relatorio2
     */
    ControladoraMovimentacao controladoraMovimentacao;
    String ano;

    public Relatorio1() {
        initComponents();
        controladoraMovimentacao = new ControladoraMovimentacao();
        carregarVeiculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboBoxVeiculos = new javax.swing.JComboBox<>();
        btGerarRelatorio = new javax.swing.JToggleButton();

        setBackground(new java.awt.Color(220, 227, 238));

        jLabel4.setFont(new java.awt.Font("DIN Alternate", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 139, 0));
        jLabel4.setText("GynLog");

        jLabel1.setFont(new java.awt.Font("DIN Alternate", 1, 18)); // NOI18N
        jLabel1.setText("Soluções");

        jLabel8.setFont(new java.awt.Font("DIN Alternate", 0, 24)); // NOI18N
        jLabel8.setText("Selecione o veículo");

        jLabel2.setBackground(new java.awt.Color(255, 153, 0));
        jLabel2.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 139, 0));
        jLabel2.setText("Veículo");

        comboBoxVeiculos.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            }
        });

        btGerarRelatorio.setText("Gerar Relatório");
        btGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 287,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(28, 28, 28)
                                                .addComponent(comboBoxVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4,
                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                        .addComponent(btGerarRelatorio)
                                                        .addGap(182, 182, 182)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(comboBoxVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(btGerarRelatorio)
                                .addContainerGap(21, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxMesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_comboBoxMesActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_comboBoxMesActionPerformed

    private void btGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btGerarRelatorioActionPerformed
        // TODO add your handling code here:
        String veiculoItem = (String) comboBoxVeiculos.getSelectedItem();

        if (comboBoxVeiculos.getSelectedIndex() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Por favor, selecione um veículo.", // Mensagem corrigida
                    "Erro de Validação", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        String idVeiculo = veiculoItem.split(" - ", 2)[0].trim();

        try {
            gerarRelatorio(idVeiculo);

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ano inválido. Use 4 dígitos numéricos.", "Erro de Formato",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao gerar o relatório: " + e.getMessage(), "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    }// GEN-LAST:event_btGerarRelatorioActionPerformed

    // Local: visao_widgets.paineis_de_telas.Relatorio6.java

    private void carregarVeiculos() {
        try {
            // Modificado para usar ListaEncadeada
            ListaEncadeada<Veiculo> listaVeiculos = controladoraMovimentacao.listarVeiculos();
            comboBoxVeiculos.removeAllItems();

            if (listaVeiculos == null || listaVeiculos.estaVazia()) { // .isEmpty() alterado para .estaVazia()
                comboBoxVeiculos.addItem("Nenhum veículo disponível");
                return;
            }

            comboBoxVeiculos.addItem("Selecione um veículo");
            comboBoxVeiculos.setSelectedIndex(0);

            for (Veiculo v : listaVeiculos) {
                String itemFormatado = String.format("%s - %s, %s, %s, %d",
                        v.getIdDeVeiculo(), v.getPlaca(), v.getMarca(), v.getModelo(), v.getAnoDeFabricacao());
                comboBoxVeiculos.addItem(itemFormatado);
            }
        } catch (Exception e) {
            comboBoxVeiculos.removeAllItems();
            comboBoxVeiculos.addItem("Erro ao carregar dados.");
        }
    }

    private void gerarRelatorio(String veiculoID) throws Exception {
        try {
            // Modificado para usar ListaEncadeada
            ListaEncadeada<Movimentacao> listar = controladoraMovimentacao
                    .listarDespesasDeUmDeterminadoVeiculo(veiculoID);
            double totalGasto = controladoraMovimentacao.calcularTotalDespesasDeUmDeterminadoVeiculo(veiculoID);
            controladoraMovimentacao.gerarRelatorio1PDF(veiculoID, totalGasto, listar);
        } catch (Exception e) {
            throw new Exception(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btGerarRelatorio;
    private javax.swing.JComboBox<String> comboBoxVeiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
