/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao_widgets;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import modelos.classes.classes_visao.Model_CardRelatorio;

/**
 *
 * @author caioaraujocunha
 */
public class CardRelatorio extends javax.swing.JPanel {

    /**
     * Creates new form Card
     */

    public CardRelatorio() {
        initComponents();
        setOpaque(false);
    }

    public void setData(Model_CardRelatorio data) {
        cardTitle.setText(data.getTitle());
        cardDesc.setText(data.getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardTitle = new javax.swing.JLabel();
        cardDesc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(220, 227, 238));

        cardTitle.setBackground(new java.awt.Color(255, 255, 255));
        cardTitle.setFont(new java.awt.Font("DecoType Naskh", 0, 48)); // NOI18N
        cardTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cardTitle.setText("Title");

        cardDesc.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        cardDesc.setForeground(new java.awt.Color(255, 139, 0));
        cardDesc.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cardDesc.setText("desc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cardDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(cardTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cardDesc)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs;
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//        GradientPaint g = new GradientPaint(0, 0, color1, 0, getHeight(), color2);
//        g2.setPaint(g);
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 40, 40);
//        g2.setColor(new Color(255, 255, 255, 50));
//        g2.fillOval(getWidth() - (getHeight() / 2), 10, getHeight(), getHeight());
//        g2.fillOval(getWidth() - (getHeight() / 2) - 20, getHeight() / 2 + 20, getHeight(), getHeight());
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cardDesc;
    private javax.swing.JLabel cardTitle;
    // End of variables declaration//GEN-END:variables
}
