/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package visao_widgets;

import modelos.classes.classes_visao.Model_Menu;
import themes.Theme;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author caioaraujocunha
 */
public class MenuItem extends javax.swing.JPanel {

    private boolean selected;
    private Model_Menu data;

    public MenuItem(Model_Menu data) {
        initComponents();
        setOpaque(false);
        this.data = data;

        if (data.getType() != Model_Menu.MenuType.TITLE) {
            lbIcon.setIcon(data.selecionarIconeCinza());
            lbName.setText(data.getName());
        } else {
            lbName.setFont(new Font("sansserif", Font.BOLD, 12));
        }
    }

    public Model_Menu getModel_Menu() {
        return data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void setSelected(boolean selected) {
        this.selected = selected;

        if (selected) {
            lbName.setForeground(Theme.SELECTED_MENU_ITEM);
            lbName.setFont(lbName.getFont().deriveFont(Font.BOLD));
            lbIcon.setIcon(data.selecionarIconeSelected());
        } else {
            lbName.setForeground(new Color(98, 103, 109));
            lbName.setFont(lbName.getFont().deriveFont(Font.PLAIN));
            lbIcon.setIcon(data.selecionarIconeCinza());
        }

        repaint();
    }

    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIcon = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();

        lbIcon.setForeground(new java.awt.Color(255, 255, 255));

        lbName.setBackground(new java.awt.Color(98, 103, 109));
        lbName.setFont(new java.awt.Font("Arial Hebrew", 0, 14)); // NOI18N
        lbName.setForeground(new java.awt.Color(98, 103, 109));
        lbName.setText("Menu Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lbIcon)
                                .addGap(18, 18, 18)
                                .addComponent(lbName)
                                .addContainerGap(25, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbIcon, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbName, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics grphcs) {
        if (selected) {
            Graphics2D g2 = (Graphics2D) grphcs;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            g2.setColor(Color.WHITE);
            g2.fillRoundRect(0, 0, getWidth(), getHeight(), 20, 20);
        }
        super.paintComponent(grphcs);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables
}
